window.KAOYAN_WORDS = [
  { word: 'abandon', meaning: '放弃；抛弃', example: 'Do not abandon your long-term plan lightly.' },
  { word: 'acquire', meaning: '获得；习得', example: 'Reading helps you acquire new knowledge.' },
  { word: 'adequate', meaning: '足够的；适当的', example: 'Sleep is adequate support for recovery.' },
  { word: 'advocate', meaning: '提倡；拥护', example: 'Many teachers advocate active learning.' },
  { word: 'alter', meaning: '改变；更改', example: 'A small habit can alter your routine.' },
  { word: 'analyze', meaning: '分析', example: 'We should analyze the problem calmly.' },
  { word: 'approach', meaning: '方法；接近', example: 'This approach is practical and clear.' },
  { word: 'assess', meaning: '评估', example: 'It is important to assess the risk first.' },
  { word: 'assume', meaning: '假设；认为', example: 'Do not assume the result too early.' },
  { word: 'attach', meaning: '附上；重视', example: 'People attach importance to details.' },
  { word: 'attain', meaning: '达到；获得', example: 'Patience helps you attain the goal.' },
  { word: 'attribute', meaning: '归因于；属性', example: 'She attributes success to persistence.' },
  { word: 'bias', meaning: '偏见；偏向', example: 'We should avoid personal bias.' },
  { word: 'capture', meaning: '捕捉；记录', example: 'The report captures the key issue.' },
  { word: 'collapse', meaning: '崩溃；倒塌', example: 'The old system may collapse under pressure.' },
  { word: 'compile', meaning: '汇编；编纂', example: 'They compile the data every week.' },
  { word: 'conceive', meaning: '想象；设想', example: 'It is hard to conceive such a change.' },
  { word: 'conduct', meaning: '进行；行为', example: 'The team will conduct a survey.' },
  { word: 'confirm', meaning: '确认；证实', example: 'Please confirm the final date.' },
  { word: 'constrain', meaning: '限制；约束', example: 'Time constraints affect the project.' },
  { word: 'consult', meaning: '咨询；查阅', example: 'You can consult the reference book.' },
  { word: 'consume', meaning: '消耗；消费', example: 'This task consumes too much energy.' },
  { word: 'contemporary', meaning: '当代的；同时代的人', example: 'The issue is highly contemporary.' },
  { word: 'convince', meaning: '说服', example: 'Facts can convince more people.' },
  { word: 'crucial', meaning: '至关重要的', example: 'Practice is crucial to improvement.' },
  { word: 'decline', meaning: '下降；拒绝', example: 'Sales began to decline last year.' },
  { word: 'dedicate', meaning: '致力于', example: 'She dedicated herself to research.' },
  { word: 'define', meaning: '定义；明确', example: 'We need to define the task clearly.' },
  { word: 'demonstrate', meaning: '证明；展示', example: 'The chart demonstrates the trend.' },
  { word: 'derive', meaning: '获得；源于', example: 'Many words derive from Latin.' },
  { word: 'devote', meaning: '投入；奉献', example: 'He devoted time to daily reading.' },
  { word: 'diminish', meaning: '减少；削弱', example: 'Confidence may diminish under stress.' },
  { word: 'distinct', meaning: '明显不同的；清晰的', example: 'The two ideas are distinct.' },
  { word: 'dominate', meaning: '支配；占优势', example: 'Digital tools dominate the market.' },
  { word: 'eliminate', meaning: '消除；淘汰', example: 'We should eliminate needless steps.' },
  { word: 'emerge', meaning: '出现；显现', example: 'New problems may emerge later.' },
  { word: 'emphasize', meaning: '强调', example: 'Teachers emphasize critical thinking.' },
  { word: 'enable', meaning: '使能够', example: 'The app enables quick access.' },
  { word: 'encounter', meaning: '遇到；遭遇', example: 'Everyone may encounter setbacks.' },
  { word: 'enhance', meaning: '提高；增强', example: 'Feedback can enhance performance.' },
  { word: 'establish', meaning: '建立；确立', example: 'They established a new system.' },
  { word: 'evaluate', meaning: '评估；评价', example: 'We should evaluate the options.' },
  { word: 'exceed', meaning: '超过', example: 'The cost exceeded our estimate.' },
  { word: 'exhibit', meaning: '展示；表现出', example: 'The results exhibit a clear pattern.' },
  { word: 'expand', meaning: '扩大；扩展', example: 'Reading expands your vocabulary.' },
  { word: 'exploit', meaning: '利用；开发', example: 'We should exploit available resources.' },
  { word: 'facilitate', meaning: '促进；使便利', example: 'Notes facilitate later review.' },
  { word: 'fundamental', meaning: '基本的；根本的', example: 'Trust is fundamental to teamwork.' },
  { word: 'generate', meaning: '产生；生成', example: 'Discussion can generate new ideas.' },
  { word: 'gradual', meaning: '逐渐的', example: 'Progress is often gradual.' },
  { word: 'guarantee', meaning: '保证', example: 'Effort cannot guarantee success, but it helps.' },
  { word: 'highlight', meaning: '强调；突出', example: 'The report highlights the challenge.' },
  { word: 'ignore', meaning: '忽视；不理会', example: 'Do not ignore early warning signs.' },
  { word: 'illustrate', meaning: '说明；阐明', example: 'The example illustrates the rule.' },
  { word: 'impose', meaning: '施加；强加', example: 'Rules may impose limits on action.' },
  { word: 'indicate', meaning: '表明；指示', example: 'The data indicates a change.' },
  { word: 'inevitable', meaning: '不可避免的', example: 'Some pressure is inevitable.' },
  { word: 'infer', meaning: '推断', example: 'We can infer the reason from the result.' },
  { word: 'integrate', meaning: '整合；融入', example: 'The tool integrates several functions.' },
  { word: 'interpret', meaning: '解释；理解', example: 'Different people interpret it differently.' },
  { word: 'justify', meaning: '证明…合理', example: 'Can you justify the decision?' },
  { word: 'maintain', meaning: '维持；保持', example: 'It is hard to maintain focus all day.' },
  { word: 'modify', meaning: '修改；更改', example: 'We can modify the plan tomorrow.' },
  { word: 'notion', meaning: '概念；看法', example: 'He challenged the old notion.' },
  { word: 'obtain', meaning: '获得', example: 'You can obtain the data online.' },
  { word: 'participate', meaning: '参与', example: 'More students participate this year.' },
  { word: 'perceive', meaning: '感知；认为', example: 'People perceive risk in different ways.' },
  { word: 'persist', meaning: '坚持；持续存在', example: 'If you persist, progress will come.' },
  { word: 'potential', meaning: '潜力；潜在的', example: 'She has great potential in research.' },
  { word: 'precise', meaning: '精确的', example: 'A precise answer saves time.' },
  { word: 'predict', meaning: '预测', example: 'It is hard to predict the outcome.' },
  { word: 'preserve', meaning: '保护；保存', example: 'We should preserve useful records.' },
  { word: 'primary', meaning: '主要的；首要的', example: 'Safety is our primary concern.' },
  { word: 'promote', meaning: '促进；推广', example: 'Exercise promotes better sleep.' },
  { word: 'prompt', meaning: '促使；迅速的', example: 'The message prompted a quick reply.' },
  { word: 'pursue', meaning: '追求；从事', example: 'She decided to pursue further study.' },
  { word: 'recover', meaning: '恢复；找回', example: 'You will recover after enough rest.' },
  { word: 'reform', meaning: '改革；改进', example: 'The policy aims to reform education.' },
  { word: 'reinforce', meaning: '加强；巩固', example: 'Practice reinforces memory.' },
  { word: 'relevant', meaning: '相关的', example: 'Please provide relevant details.' },
  { word: 'require', meaning: '需要；要求', example: 'The task requires patience.' },
  { word: 'retain', meaning: '保留；记住', example: 'Review helps retain new words.' },
  { word: 'reveal', meaning: '揭示；显示', example: 'The study reveals a gap.' },
  { word: 'significant', meaning: '重要的；显著的', example: 'There was a significant increase.' },
  { word: 'strategy', meaning: '策略；战略', example: 'We need a better strategy.' },
  { word: 'submit', meaning: '提交；屈服', example: 'Please submit the form today.' },
  { word: 'sufficient', meaning: '足够的', example: 'Ten minutes is not sufficient.' },
  { word: 'sustain', meaning: '维持；支撑', example: 'It is hard to sustain high focus.' },
  { word: 'transform', meaning: '改变；转化', example: 'Technology can transform learning.' },
  { word: 'undergo', meaning: '经历；遭受', example: 'The system will undergo testing.' },
  { word: 'utilize', meaning: '利用', example: 'We should utilize the spare time well.' },
  { word: 'valid', meaning: '有效的；正当的', example: 'Your concern is completely valid.' },
  { word: 'vary', meaning: '变化；不同', example: 'Results vary from person to person.' }
];